### ISSUE TITLE
legendary auth "Getting exchange code failed" in CMD

### ISSUE THREAD

**Issue by volttics** [derrod/legendary#331] opened 2021-09-03 14:06 UTC
![Capture](https://user-images.githubusercontent.com/90051049/132018378-4e76a74e-e90e-4816-bdf2-707da9630a9b.PNG)

so when i type in legendary auth, it gives me this error code. I deleted legendary and reinstalled it. It still happens. How do i fix

Edit: It was working before. One of my buddies installed epic on my computer yesterday and i uninstalled it after he was finished using it. Now it doesnt work

**Comment by CommandMC** [comment] 2021-09-03 14:06
Duplicate of #329

**Closed** 2021-09-03 16:26 UTC
