### ISSUE TITLE
i have enough space

### ISSUE THREAD

**Issue by Spike1377** [derrod/legendary#565] opened 2023-06-04 08:27 UTC
did you endup seeing what i wrote last time #553
it still happens
![image](https://github.com/derrod/legendary/assets/113913612/6c940108-cf39-44b2-95a4-051f15bc44f0)
one update dose not take 33.53gigs if i reinstall the hole game i can get the update, you gotta fix that

**Comment by derrod** [comment] 2023-06-04 08:38
Duplicate of #553

**Closed by derrod** 2023-06-04 08:38 UTC
