### ISSUE TITLE
Add support for linking an Ubisoft account.

### ISSUE THREAD

**Issue by LinoBigatti** [derrod/legendary#115] opened 2020-10-02 02:36 UTC
Under the normal epic games launcher, when you try to install a game that requires uplay, it prompts you to link your ubisoft account to your epic games one. This is great and all, but if you cant have access to the epic games launcher at all it is very frustrating to not be able to play some games. Afaik you only need an url to link those two together so it shouldnt be too difficult to implement.

**Comment by Jawschamp** [comment] 2020-10-02 04:10
> Under the normal epic games launcher, when you try to install a game that requires uplay, it prompts you to link your ubisoft account to your epic games one. This is great and all, but if you cant have access to the epic games launcher at all it is very frustrating to not be able to play some games. Afaik you only need an url to link those two together so it shouldnt be too difficult to implement.

Great point I'm sure Rodney will have a solution soon!

**Comment by derrod** [comment] 2020-10-02 05:08
Duplicate of #69 (nice)

**Closed by derrod** 2020-10-02 05:08 UTC
