### ISSUE TITLE
download dont work 

### ISSUE THREAD

**Issue by KliiMTV** [derrod/legendary#256] opened 2021-03-20 17:25 UTC
[Core] INFO: Overriding manifest with "http://epicgames-download1.akamaized.net/Builds/Fortnite/CloudDir/qSfz1yvL2a694c0e864a4e2aadd0229121cde46c"
Traceback (most recent call last):
  File "legendary\cli.py", line 1375, in <module>
  File "legendary\cli.py", line 1343, in main
  File "legendary\cli.py", line 595, in install_game
  File "legendary\core.py", line 723, in prepare_download
  File "legendary\core.py", line 669, in get_uri_manifest
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://epicgames-download1.akamaized.net/Builds/Fortnite/CloudDir/qSfz1yvL2a694c0e864a4e2aadd0229121cde46c
[10896] Failed to execute script cli

**Comment by derrod** [comment] 2021-03-20 17:31
Duplicate of #152 and many more...

**Closed** 2021-03-20 17:31 UTC
