### ISSUE TITLE
Minimum required memory cache to install game is over 23Gb

### ISSUE THREAD

**Issue by Radet5** [derrod/legendary#158] opened 2020-12-17 05:29 UTC
Hi! Trying to get some epic games running on Arch Linux and Legendary seems like the best bet (thx for making it!). Tried installing the only one I have via `legendary install  bcc75c246fe04e45b0c1f1c3fd52503a --enable-reordering` and I got this error:

> [Core] INFO: Trying to re-use existing login session...
> [cli] INFO: Preparing download...
> [Core] INFO: Parsing game manifest...
> [Core] INFO: Install path: /mnt/ssd/radet5/legendary/PillarsOfEternity
> [Core] INFO: Download order optimizations are enabled.
> [DLM] WARNING: Manifest contains too many files, processing optimizations will be disabled.
> Traceback (most recent call last):
>   File "/usr/bin/legendary", line 33, in <module>
>     sys.exit(load_entry_point('legendary-gl==0.20.4', 'console_scripts', 'legendary')())
>   File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 1325, in main
>     cli.install_game(args)
>   File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 594, in install_game
>     dlm, analysis, igame = self.core.prepare_download(game=game, base_game=base_game, base_path=args.base_path,
>   File "/usr/lib/python3.9/site-packages/legendary/core.py", line 801, in prepare_download
>     anlres = dlm.run_analysis(manifest=new_manifest, old_manifest=old_manifest,
>   File "/usr/lib/python3.9/site-packages/legendary/downloader/manager.py", line 376, in run_analysis
>     raise MemoryError(f'Current shared memory cache is smaller than required! {shared_mib} < {required_mib}. '
> MemoryError: Current shared memory cache is smaller than required! 4096.0 MiB < 23385.0 MiB. Try running legendary with the --enable-reordering flag to reduce memory usage.

I feel like this has to be a bug? I know some people have that much RAM but I have like 8Gb

Config.ini in case it's helpful:

> [Legendary]
> max_memory = 4096
> install_dir = /mnt/ssd/radet5/legendary
> 
> [default]
> wine_prefix = /mnt/ssd/radet5/legendary/.wine

**Comment by derrod** [comment] 2020-12-17 05:34
Duplicate of #149 and #151, see https://github.com/derrod/legendary/issues/17#issuecomment-743701890

**Closed by derrod** 2020-12-17 05:34 UTC

**Comment by emansom** [comment] 2023-01-08 21:49
Can `--enable-reordering` become the default?

Was installing GTA V and ran into this issue.
