### ISSUE TITLE
Rocket League crashes at Upload Save Data during an online match

### ISSUE THREAD

**Issue by lehleh** [derrod/legendary#367] opened 2021-11-06 05:17 UTC
## Platform

Operating system and version:
Arch Linux 5.14.16-arch1-1
Legendary version (`legendary -V`):
legendary version "0.20.10", codename "Black Mesa East"
## Expected Behavior

Doesn't crash
## Current Behavior

Only happens during matchmade games, usually happens early into the game, first minute or 2.Then leads to Wine error.
```
ScriptWarning, Something went wrong uploading save data 94305abc5e2947f8a471e643bacdbd7a RLSaveData
        EOSOnlineStorageUploader_TA Transient.SaveData_TA_1:EOSOnlineStorageUploader_TA_0
        Function TAGame.EOSOnlineStorageUploader_TA:UploadSaveData:0701
Script call stack:
        Function TAGame.SaveData_TA:HandleMapChange
        Function TAGame.SaveData_TA:UploadSaveData
        Function TAGame.EOSOnlineStorageUploader_TA:UploadSaveData


wine: Unhandled page fault on write access to 0000000000000000 at address 00000001C8DFF4EF (thread 0084), starting debugger...
0078:err:wineusb:event_thread_proc Error handling events: System call interrupted (perhaps due to signal)
0078:err:wineusb:event_thread_proc Error handling events: System call interrupted (perhaps due to signal)
0228:err:ntdll:RtlpWaitForCriticalSection section 0000000253CC6100 "../src-wine/dlls/xinput1_3/main.c: controllers[0].crit" wait timed out in thread 0228, blocked by 0104, retrying (60 sec)
```

## Steps to Reproduce

1. Enter a online matchmaking game.
2. Wait for a few seconds to 1/2 minute
3. Crash

**Comment by CommandMC** [comment] 2021-11-22 19:44
Not a Legendary issue.
![image](https://user-images.githubusercontent.com/34034631/142924843-271b8337-8049-4499-8e2f-e711762ee54b.png)

Also, you're using a pretty old Legendary version. Might wanna update that

**Comment by derrod** [comment] 2022-01-20 00:57
Could you try again with a build from master? I added an additional command line parameter the Epic Launcher started setting and I wonder if rocket league needs that for some reason.

Artifacts can be found here: https://github.com/derrod/legendary/actions/runs/1713415655

**Comment by derrod** [comment] 2022-01-25 07:40
I'll just close this for now given that it's a game issue in the first place (that I was unable to reproduce) and OP has been unresponsive.

**Closed by derrod** 2022-01-25 07:40 UTC
