### ISSUE TITLE
bioshock 1 remastered  (and maybe the other Bioshocks too) can't work with current version legendary alone

### ISSUE THREAD

**Issue by Trokinos** [derrod/legendary#432] opened 2022-05-26 17:42 UTC
Using Window 10 and latest "0.20.25 - Our Benefactors" version of Legendary.

This week on the epic store they are giving away for free "Bioshock : The Collection" that is the 3 following games : 
Bioshock 1 Remastered
Bioshock 2 Remastered
Bioshock Infinite Definitive Edition

I only could try Bioshock 1 Remastered so far, but i suspect the problem will be the same with the other 2 as unfortunately there's 2K involved and they parasited all their games with their 2K Launcher in the last couple of years.

The "2K Launcher" lead into the  same situation as xcom2 reported here : 
https://github.com/derrod/legendary/issues/422
The exe override bypassing trick mentionned in the report works too so you can bypass the horrible 2K Launcher and start the game, in the case of Bioshock 1 Remastered it's 
` --override-exe Build/FinalEpic/BioshockHD.exe`

But unfortunately unlike xcom2 there's a secondary problem that will prevent you to play :
At some point of the gameplay the game will pause and a window popup "you must play/start this game with the Epic Launcher" will appear. 
And you can't continue to play as once the popup is exited, the game close itself automatically.  
This popup didn't happened all the time i tried at the same point, first time it did was when the player was swimming up after the plane initial crash, and the second time it happened inside the bathysphere you get in from the tower after swimming up from the plane crash, so i guess it can simply happen anytime to prevent you to continue to play without the epic launcher installed.

**Comment by Trokinos** [comment] 2022-05-26 18:06
Seems to have solved the window popup problem preventing to play.
When i launch the game, as it sometime happens there's a page in my browser launched by it, basically asking me to associate the game to my epic account, this has happened in the past with very few games, never bothered with it (why ask me that considering the game is already in my account) .  
But this time i decided to accept.  
  
And since then there's no more window popup about me having to use the epic launcher to play it before quitting the game automatically, i've been playing for some time without problems.

So it seems for this game you have to accept that linking thing (noticed in the main menu instead of saying that my 2K Account is Offline it will now say "not associated" (or something like that as i don't play in english).

For the exe override the report is still valid.

**Comment by derrod** [comment] 2022-05-26 21:13
Essentially just a duplicate of #422 since this is also down to the stupid 2K Launher. Overriding the exe is something I want to do automatically for those titles, but it's not implemented yet.

**Closed by derrod** 2022-05-26 21:13 UTC

**Comment by Trokinos** [comment] 2022-05-27 01:46
I added the bioshock 1&2 remastered entries in the wiki for the game workarounds
But only for the windows section as i don't know if it works or need workarounds on linux and macOS

**Comment by snazzer** [comment] 2022-05-27 19:08
| When i launch the game, as it sometime happens there's a page in my browser launched by it, basically asking me to associate the game to my epic account, this has happened in the past with very few games

I don't think I see this popup in SteamDeck so probably need some way to do this association in linux/steamdeck. If there's a way to trigger it would be good to know.

**Comment by snazzer** [comment] 2022-05-28 16:04
Looks like offline mode seems to work to avoid the popup.

**Comment by josue2363** [comment] 2022-05-30 00:34
> I added the bioshock 1&2 remastered entries in the wiki for the game workarounds But only for the windows section as i don't know if it works or need workarounds on linux and macOS

Hello, I can confirm that the information you added to kiwi to fix "bioshock 1&2 remastered" games running also works (and is also required) on Linux. I tested this with Regata OS (based on openSUSE). Thank you very much!

**Comment by Trokinos** [comment] 2022-05-30 14:30
> > I added the bioshock 1&2 remastered entries in the wiki for the game workarounds But only for the windows section as i don't know if it works or need workarounds on linux and macOS
> 
> Hello, I can confirm that the information you added to kiwi to fix "bioshock 1&2 remastered" games running also works (and is also required) on Linux. I tested this with Regata OS (based on openSUSE). Thank you very much!

thank you for confirming that not only it works on Linux but is necessary too, so i added the entries to the Linux and MacOS (as i guess due to the 2K Launcher it will be necessary for all OS anyways) 

> Looks like offline mode seems to work to avoid the popup.
Never tried the offline mode , thanks for the reminder as i'll have to give a try.
