### ISSUE TITLE
Traceback when acces_token has expired

### ISSUE THREAD

**Issue by timfretz** [derrod/legendary#519] opened 2022-12-18 22:11 UTC
## Platform
Operating system and version: `ChimeraOS 37 (1877cb7)`
Legendary version (`legendary -V`): `legendary version "0.20.31", codename "Dark Energy (hotfix #5)"`

## Expected Behavior
Prompt user as necessary to reset expired access_tokens.

## Current Behavior
Traceback:
```
[gamer@chimeraos ~]$ legendary list-games --csv
[cli] INFO: Logging in...
[Core] INFO: Logging in...
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.31', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.10/site-packages/legendary/cli.py", line 2972, in main
    cli.list_games(args)
  File "/usr/lib/python3.10/site-packages/legendary/cli.py", line 190, in list_games
    if not self.core.login():
  File "/usr/lib/python3.10/site-packages/legendary/core.py", line 236, in login
    userdata = self.egs.start_session(self.lgd.userdata['refresh_token'])
  File "/usr/lib/python3.10/site-packages/legendary/api/egs.py", line 128, in start_session
    self.session.headers['Authorization'] = f'bearer {j["access_token"]}'
KeyError: 'access_token'
```

## Steps to Reproduce
1. Use Legendary to authenticate with Epic Store
2. Don't touch system for several weeks
3. Attempt to run `list-games --csv`. Also tried `legendary status` and `legendary auth`
4. Results in traceback above

Note I am running Legendary via Chimera normally, only started running `legendary ...` directly to debug.

## Additional information
Workaround: Was able to move /home/gamer/.config/legendary/user.json out of the way. Then accessed https://chimera.local/library/epic-store and was prompted to login to epic and provide a new auth key. After doing so, user.json was re-created with a valid token and both legendary and chimera are working as expected.

Old user.json does not seem corrupted or malformed in any way. Just has an expired token:
```
<   "expires_at": "2022-12-11T08:22:01.543Z",
---
>   "expires_at": "2022-12-19T05:34:11.292Z",
```

**Comment by CommandMC** [comment] 2022-12-18 22:14
Duplicate of #512, #513, #514, #516, and probably others

**Closed** 2022-12-18 22:25 UTC
