### ISSUE TITLE
Game launched with legendary doesn't detect keyboard input after losing focus

### ISSUE THREAD

**Issue by TabulateJarl8** [derrod/legendary#211] opened 2021-01-17 19:05 UTC
Hi, I noticed a strange bug today. I installed the Escapists 2 with legendary, and it works great except for one issue. If the game at all loses focus, keyboard input ceases to work. Let me know if there's any debug info I can give you. I'm running legendary version `"0.20.6", codename "A Red Letter Day"` on Manjaro Linux with the Linux 5.10.2 headers.

**Comment by derrod** [comment] 2021-01-17 19:21
Might be a duplicate of #103, either way not an issue on Legendary's end but some Linux stupidity. Maybe try to see if this help: https://forum.winehq.org/viewtopic.php?t=20646

**Closed by derrod** 2021-01-17 19:21 UTC

**Comment by TabulateJarl8** [comment] 2021-01-18 02:43
Just putting this here for other people who have this issue, the issue seems to go away if you change the game to run in windowed mode in the games settings, and you can just remove the window borders if you don't want those using your OS.
