### ISSUE TITLE
KeyError: 'access_token' when trying to log in.

### ISSUE THREAD

**Issue by AZthemute** [derrod/legendary#516] opened 2022-12-14 20:09 UTC
## Platform

Operating system and version: Windows 10 Home 21H2
Legendary version (`legendary -V`): 0.20.31

## Expected Behavior

The program doesn't crash.
## Current Behavior

```
C:\Users\AZ\Downloads> legendary.exe auth
[cli] INFO: Testing existing login data if present...
[Core] INFO: Logging in...
Traceback (most recent call last):
  File "legendary\cli.py", line 3069, in <module>
  File "legendary\cli.py", line 2978, in main
  File "legendary\cli.py", line 81, in auth
  File "legendary\core.py", line 236, in login
  File "legendary\api\egs.py", line 128, in start_session
KeyError: 'access_token'
[7444] Failed to execute script 'cli' due to unhandled exception!
```
And a crash.

## Steps to Reproduce

I did nothing before this started happening, I was using legendary without any issues just the night before any issues started.. This is either an issue with Epic changing some stuff server-side or an invalid login key. If it is something to do with my login key, I don't know how to refresh it and `legendary auth` just crashes with the same error.

**Comment by derrod** [comment] 2022-12-14 20:11
Duplicate of #512 #513 #514. Login via the website first, then try again.

**Closed by derrod** 2022-12-14 20:11 UTC
