### ISSUE TITLE
Game list is not updating

### ISSUE THREAD

**Issue by Chichi0807** [derrod/legendary#209] opened 2021-01-15 15:36 UTC
Not sure if I'm doing anything wrong, but after I received a free copy of star wars battlefront II from the webpage of epic games, I did not see it in the list of games of "legendary list-games". I've tried logging out and logging in, but does not work. 
![螢幕擷取畫面 2021-01-15 233417](https://user-images.githubusercontent.com/53339198/104746564-68c86900-578a-11eb-911a-d9ea366f29a9.png)
![螢幕擷取畫面 2021-01-15 233443](https://user-images.githubusercontent.com/53339198/104746570-69f99600-578a-11eb-977b-67c4db19c1ef.png)

**Comment by derrod** [comment] 2021-01-15 15:36
Duplicate of #202

**Comment by CommandMC** [comment] 2021-01-15 15:36
See https://github.com/derrod/legendary/issues/202

**Closed** 2021-01-15 15:36 UTC

**Comment by Chichi0807** [comment] 2021-01-15 15:39
Oops, did not see that. Sorry and thank you!
